Repository AkatsukiLabs/DojoByExample, pull requests merged in 2025-03, with the labels that each got.

#46 feat#4: player model
  scripts/src/lib.cairo
  scripts/src/models/model.cairo
  scripts/src/models/player.cairo
Labels: Approved

#47 feat: added the Food model
  scripts/src/lib.cairo
  scripts/src/models/food.cairo
Labels: Approved

#48 chore: added enum Beast
  scripts/src/lib.cairo
  scripts/src/models/model.cairo
  scripts/src/types/beast_type.cairo
Labels: Approved

#50 Feat: Create Model Beats
  scripts/src/lib.cairo
  scripts/src/models/beast.cairo
Labels: Approved

#49 feat: models for Tournament
  scripts/src/constants.cairo
  scripts/src/lib.cairo
  scripts/src/models/matchup.cairo
  scripts/src/models/playerstats.cairo
  scripts/src/models/reward.cairo
  scripts/src/models/tournament.cairo
  scripts/src/store.cairo
Labels: Approved

#52 Beast Stats Model Implementation
  scripts/src/models/beaststats.cairo
Labels: Approved

#51 Feat #35 tournament models tests
  scripts/src/lib.cairo
  scripts/src/models/beast.cairo
  scripts/src/models/food.cairo
  scripts/src/models/matchup.cairo
  scripts/src/models/model.cairo
  scripts/src/models/playerstats.cairo
  scripts/src/models/reward.cairo
  scripts/src/models/tournament.cairo
  scripts/src/systems/actions.cairo
  scripts/src/tests/test_tournament.cairo
  scripts/src/tests/test_world.cairo
  scripts/src/types/beast_type.cairo
Labels: Approved

#54 Create Model Leaderboard
  scripts/src/models/leaderboard.cairo
  scripts/src/types/leaderboard_type.cairo
  scripts/src/types/ranking_criteria_type.cairo
  scripts/src/types/time_period_type.cairo
Labels: Approved

#56 Feat: Implement Achievement Model
  scripts/src/lib.cairo
  scripts/src/models/achievement.cairo
Labels: Approved

#58 Add FoodType Enum with Conversion Traits and Integrate into Food Struct
  scripts/src/types/food_type.cairo
Labels: Approved

#44 feat: create RewardType enum
  .tool-versions
  dojo_examples/combat_game/src/models/player.cairo
  dojo_examples/combat_game/src/types/reward_type.cairo
Labels: Changes Requested

#68 fix: TypeScript definitions for Babel and ESTree modules
  .tool-versions
  package.json
  pnpm-lock.yaml
  tsconfig.json
  types/estree-jsx.d.ts
  types/types.d.ts
Labels: bug, Core Dev
